#!/usr/bin/env python3
"""
Beach Ice Cream Generator
Generates 180 family-friendly Jeopardy-format questions about beach ice cream, frozen treats, and snacks
30 questions per difficulty level (6 levels total)
"""

import json

def generate_beach_ice_cream_questions():
    data = {
        "category": "Beach Ice Cream & Frozen Treats",
        "theme": "beach",
        "category_id": "beach_ice_cream",
        "research_basis": "Culinary arts, frozen desserts, beach culture, summer traditions, food history, sensory science, global frozen treats",
        "audiences": {
            "level_1_easy_200": [
                {"clue": "This cold treat on a stick is a favorite at the beach", "correctQuestion": "What is a popsicle?", "value": 200},
                {"clue": "You use this tool to scoop ice cream into a cone", "correctQuestion": "What is an ice cream scoop?", "value": 200},
                {"clue": "This sweet frozen treat comes in flavors like vanilla and chocolate", "correctQuestion": "What is ice cream?", "value": 200},
                {"clue": "This waffle cone holds ice cream at the beach concession stand", "correctQuestion": "What is a cone?", "value": 200},
                {"clue": "This beach snack on a stick drips down your hand in the sun", "correctQuestion": "What is a popsicle (or ice cream)?", "value": 200},
                {"clue": "This colorful frozen treat is shaped like a rocket ship", "correctQuestion": "What is a rocket pop?", "value": 200},
                {"clue": "This creamy frozen dessert melts faster at the beach than at home", "correctQuestion": "What is ice cream?", "value": 200},
                {"clue": "These tiny round balls go on top of ice cream at the beach shack", "correctQuestion": "What are sprinkles?", "value": 200},
                {"clue": "This frozen treat between two cookies is called an ice cream sandwich", "correctQuestion": "What is an ice cream sandwich?", "value": 200},
                {"clue": "You get this cold, painful feeling if you eat ice cream too fast", "correctQuestion": "What is a brain freeze?", "value": 200},
                {"clue": "This Italian word describes creamy frozen dessert similar to ice cream", "correctQuestion": "What is gelato?", "value": 200},
                {"clue": "These beach treats come in orange, white, and red stripes", "correctQuestion": "What are popsicles (or ice pops)?", "value": 200},
                {"clue": "This frozen pudding pop was a famous 1980s treat from Bill Cosby", "correctQuestion": "What is a pudding pop?", "value": 200},
                {"clue": "This French frozen dessert has no dairy or cream in it", "correctQuestion": "What is sorbet?", "value": 200},
                {"clue": "This beach drink is half lemonade, half iced tea, and perfect on hot days", "correctQuestion": "What is an Arnold Palmer?", "value": 200},
                {"clue": "This creamy frozen dessert is made with yogurt instead of cream", "correctQuestion": "What is frozen yogurt?", "value": 200},
                {"clue": "This Mexican beach treat is shaved ice covered in fruit syrup and condensed milk", "correctQuestion": "What is a raspado (or shaved ice)?", "value": 200},
                {"clue": "These frozen confections come in tropical flavors like mango and pineapple", "correctQuestion": "What are popsicles (or ice pops)?", "value": 200},
                {"clue": "This crunchy stick holds your ice cream at the beach", "correctQuestion": "What is a cone (or sugar cone)?", "value": 200},
                {"clue": "This sweet frozen pop is shaped like your favorite cartoon character", "correctQuestion": "What is a character-shaped popsicle (or Otter Pop)?", "value": 200},
                {"clue": "This beach vendor sells this cold treat from a cart with an umbrella", "correctQuestion": "What is ice cream (or frozen treats)?", "value": 200},
                {"clue": "This cold, creamy dessert pairs perfectly with warm beach pie", "correctQuestion": "What is ice cream?", "value": 200},
                {"clue": "These small frozen balls covered in chocolate are called this", "correctQuestion": "What are chocolate-covered ice cream balls (or bonbons)?", "value": 200},
                {"clue": "This tropical frozen treat is made from coconut milk at beach resorts", "correctQuestion": "What is coconut ice cream?", "value": 200},
                {"clue": "This Spanish frozen chocolate drink is perfect with beach pastries", "correctQuestion": "What is hot chocolate (or chocolate con churros)?", "value": 200},
                {"clue": "These beach snacks come on a stick and taste like creamsicles", "correctQuestion": "What is a creamsicle?", "value": 200},
                {"clue": "This frozen treat on a stick tastes like orange and vanilla together", "correctQuestion": "What is a creamsicle (or otter pop)?", "value": 200},
                {"clue": "This cold dessert is served in a cone, cup, or on a stick at the beach", "correctQuestion": "What is ice cream?", "value": 200},
                {"clue": "This beach snack brand makes popsicles shaped like animals", "correctQuestion": "What are Otter Pops?", "value": 200},
                {"clue": "This frozen pudding treat was a famous 1980s nostalgic snack", "correctQuestion": "What is a pudding pop?", "value": 200},
            ],
            "level_2_easy_400": [
                {"clue": "This Japanese frozen treat is made from shaved ice and sweet bean paste", "correctQuestion": "What is kakigori (or shaved ice)?", "value": 400},
                {"clue": "This soft-serve ice cream is made using a special machine at the beach", "correctQuestion": "What is soft-serve ice cream?", "value": 400},
                {"clue": "This frozen dessert brand gives you a free cone on your birthday", "correctQuestion": "What is Ben & Jerry's (or Dairy Queen)?", "value": 400},
                {"clue": "This Italian frozen dessert has less air and more flavor than American ice cream", "correctQuestion": "What is gelato?", "value": 400},
                {"clue": "This tropical frozen drink is made with blended ice and fruit juice", "correctQuestion": "What is a slushie (or snow cone)?", "value": 400},
                {"clue": "This Brazilian frozen treat is made from acai berries and served in a bowl", "correctQuestion": "What is an acai bowl?", "value": 400},
                {"clue": "This frozen coffee drink is perfect for hot beach days", "correctQuestion": "What is an iced coffee (or affogato)?", "value": 400},
                {"clue": "This Asian frozen dessert made from fresh fruit has no cream", "correctQuestion": "What is sorbet (or gelato)?", "value": 400},
                {"clue": "This beach treat is ice cream sandwiched between two pieces of cake", "correctQuestion": "What is an ice cream sandwich?", "value": 400},
                {"clue": "These colorful frozen pops come in a variety pack with different flavors", "correctQuestion": "What are assorted popsicles?", "value": 400},
                {"clue": "This frozen treat is made by mixing soft-serve in a blender with candy", "correctQuestion": "What is a blizzard (or concrete)?", "value": 400},
                {"clue": "This cold beach snack is made from frozen fruit juice on a stick", "correctQuestion": "What is a popsicle (or fruit bar)?", "value": 400},
                {"clue": "This Indian frozen dessert is flavored with cardamom and pistachios", "correctQuestion": "What is kulfi?", "value": 400},
                {"clue": "This creamy frozen dessert is churned while freezing for smooth texture", "correctQuestion": "What is ice cream?", "value": 400},
                {"clue": "This beach vendor's truck plays this famous song to announce ice cream", "correctQuestion": "What is 'Turkey in the Straw' (or 'Pop Goes the Weasel')?", "value": 400},
                {"clue": "This frozen treat melts faster in summer because of this factor", "correctQuestion": "What is heat (or temperature)?", "value": 400},
                {"clue": "This frozen dessert made with milk instead of cream is healthier", "correctQuestion": "What is frozen yogurt?", "value": 400},
                {"clue": "This tropical frozen treat tastes like pineapple and coconut combined", "correctQuestion": "What is a tropical popsicle?", "value": 400},
                {"clue": "This Mexican beach drink is sweet and frozen with chili powder on top", "correctQuestion": "What is a paleta (or chili-mango popsicle)?", "value": 400},
                {"clue": "This frozen fruit bar is made with real fruit puree, not artificial flavoring", "correctQuestion": "What is a sorbet bar (or fruit bar)?", "value": 400},
                {"clue": "This frozen coffee treat combines espresso with ice cream", "correctQuestion": "What is an affogato?", "value": 400},
                {"clue": "This beach snack is cereal suspended in frozen milk", "correctQuestion": "What is a cereal-flavored popsicle?", "value": 400},
                {"clue": "This frozen treat has a crunchy cookie layer inside soft ice cream", "correctQuestion": "What is a cookie sandwich (or ice cream sandwich)?", "value": 400},
                {"clue": "This Chinese frozen dessert is made with shaved ice and fruit syrup", "correctQuestion": "What is bao bing (or shaved ice)?", "value": 400},
                {"clue": "This frozen beach treat is dipped in chocolate and rolled in nuts", "correctQuestion": "What is a chocolate-dipped ice cream cone?", "value": 400},
                {"clue": "This cold dessert is served at every ice cream parlor on a warm beach day", "correctQuestion": "What is ice cream?", "value": 400},
                {"clue": "This freeze-dried fruit snack tastes like fresh fruit but lasts longer at the beach", "correctQuestion": "What is freeze-dried fruit?", "value": 400},
                {"clue": "This frozen Greek yogurt treat is thicker and tangier than regular frozen yogurt", "correctQuestion": "What is frozen Greek yogurt?", "value": 400},
                {"clue": "This beach-friendly frozen snack comes in a pouch you squeeze into your mouth", "correctQuestion": "What is a frozen fruit squeeze (or push-pop)?", "value": 400},
                {"clue": "This colorful frozen treat glows under ultraviolet light at the beach", "correctQuestion": "What is a glow-stick popsicle?", "value": 400},
            ],
            "level_3_medium_600": [
                {"clue": "This process of adding salt and ice to a cream mixture lowers the freezing point", "correctQuestion": "What is freezing point depression?", "value": 600},
                {"clue": "This ingredient prevents ice crystals from forming in homemade beach ice cream", "correctQuestion": "What is sugar (or gelatin)?", "value": 600},
                {"clue": "This Turkish frozen dessert is made with mastic gum and has a unique stretchy texture", "correctQuestion": "What is dondurma?", "value": 600},
                {"clue": "This percentage of air whipped into ice cream affects its density and creaminess", "correctQuestion": "What is 20-50% overrun?", "value": 600},
                {"clue": "This compound in ice cream helps maintain smooth texture and prevents graininess", "correctQuestion": "What is lecithin (or guar gum)?", "value": 600},
                {"clue": "This frozen dessert made with condensed milk and shaved ice is popular in the Philippines", "correctQuestion": "What is halo-halo (or shaved ice)?", "value": 600},
                {"clue": "This technique involves churning ice cream while freezing to incorporate air and smooth texture", "correctQuestion": "What is churning?", "value": 600},
                {"clue": "This temperature in Fahrenheit is the ideal serving temperature for ice cream at the beach", "correctQuestion": "What is 6-10 degrees (Fahrenheit)?", "value": 600},
                {"clue": "This Italian tradition of layering multiple gelato flavors is called this", "correctQuestion": "What is affogato (or mixed flavors)?", "value": 600},
                {"clue": "This ratio of sugar to cream affects both sweetness and the melting point of ice cream", "correctQuestion": "What is about 20% sugar?", "value": 600},
                {"clue": "These molecules in ice cream act as emulsifiers to keep oil and water mixed smoothly", "correctQuestion": "What are fatty acids (or lecithin)?", "value": 600},
                {"clue": "This fruit pulp frozen on a stick is a popular beach treat in Latin America", "correctQuestion": "What is a paleta?", "value": 600},
                {"clue": "This French dessert uses ice cream as a base with a thin caramelized sugar shell", "correctQuestion": "What is crème brûlée ice cream?", "value": 600},
                {"clue": "This machine continuously churns ice cream for the soft texture at beach shops", "correctQuestion": "What is a soft-serve machine?", "value": 600},
                {"clue": "This preservative extends shelf life but can create a waxy mouthfeel in commercial ice cream", "correctQuestion": "What are mono and diglycerides?", "value": 600},
                {"clue": "This Asian frozen dessert made with tapioca pearls and condensed milk is chewy", "correctQuestion": "What is boba ice cream (or bing)?", "value": 600},
                {"clue": "This Middle Eastern frozen dessert can be sliced with a knife without breaking apart", "correctQuestion": "What is dondurma?", "value": 600},
                {"clue": "This temperature difference between hot beach sand and cold ice cream creates texture contrast", "correctQuestion": "What is about 100+ degrees Fahrenheit?", "value": 600},
                {"clue": "This artisanal ice cream technique uses liquid nitrogen for instant freezing", "correctQuestion": "What is liquid nitrogen freezing?", "value": 600},
                {"clue": "This frozen plant-based treat is made with coconut cream instead of dairy", "correctQuestion": "What is vegan ice cream (or coconut ice cream)?", "value": 600},
                {"clue": "This historical Roman frozen treat combined snow from mountains with fruit and honey", "correctQuestion": "What is sorbet (or Italian ice)?", "value": 600},
                {"clue": "This protein in milk helps stabilize the texture of frozen beach desserts", "correctQuestion": "What is casein (or whey)?", "value": 600},
                {"clue": "This technique of hand-churning ice cream was used before electric machines", "correctQuestion": "What is manual churning?", "value": 600},
                {"clue": "This frozen dessert made entirely from fruit juice has zero percent fat", "correctQuestion": "What is sorbet (or water ice)?", "value": 600},
                {"clue": "This Spanish frozen drink is chocolate thickened with corn starch, served cold with churros", "correctQuestion": "What is chocolate con churros (or chocolate iced)?", "value": 600},
                {"clue": "These tiny ice crystals form when ice cream is stored at inconsistent temperatures", "correctQuestion": "What is ice recrystallization (or freezer burn)?", "value": 600},
                {"clue": "This Korean shaved ice dessert topped with sweet bean paste is called this", "correctQuestion": "What is pat bingsu?", "value": 600},
                {"clue": "This percentage of fat content qualifies as premium ice cream in the United States", "correctQuestion": "What is 14% or higher?", "value": 600},
                {"clue": "This emulsifier made from egg yolks creates a rich custard-based gelato", "correctQuestion": "What is creme anglaise (or egg yolks)?", "value": 600},
                {"clue": "This process of aging ice cream base overnight improves flavor and texture development", "correctQuestion": "What is maturation (or aging)?", "value": 600},
            ],
            "level_4_medium_800": [
                {"clue": "This Taiwanese shaved ice dessert layered with condensed milk and fruit is called mua chi", "correctQuestion": "What is mua chi (or shaved ice)?", "value": 800},
                {"clue": "This ingredient derived from seaweed acts as a binder in soft-serve ice cream", "correctQuestion": "What is carrageenan (or alginate)?", "value": 800},
                {"clue": "This fermentation process creates probiotics in a cold, creamy frozen treat", "correctQuestion": "What is yogurt fermentation (frozen yogurt)?", "value": 800},
                {"clue": "This polymer from corn acts as a thickening agent in commercial ice cream products", "correctQuestion": "What is corn syrup solids (or modified corn starch)?", "value": 800},
                {"clue": "This ratio of egg yolks to cream creates the richness in authentic French ice cream", "correctQuestion": "What is about 5-7 yolks per quart of cream?", "value": 800},
                {"clue": "This Greek frozen yogurt contains live cultures and has twice the protein of regular frozen yogurt", "correctQuestion": "What is Greek frozen yogurt?", "value": 800},
                {"clue": "This Italian technique of making gelato uses less air incorporation than American ice cream", "correctQuestion": "What is traditional gelato churning?", "value": 800},
                {"clue": "This pH level change occurs when lemon juice is added to ice cream, affecting texture", "correctQuestion": "What is increased acidity?", "value": 800},
                {"clue": "This Scandinavian frozen treat made from whipped cream and sugar is piped into shapes", "correctQuestion": "What is Norwegian or Swedish ice cream?", "value": 800},
                {"clue": "This capsule-shaped frozen treat from Japan contains liquid center with fruit juice", "correctQuestion": "What is a popping candy popsicle (or bursting boba)?", "value": 800},
                {"clue": "This molecular gastronomy technique creates ice cream spheres using sodium alginate and calcium chloride", "correctQuestion": "What is spherification?", "value": 800},
                {"clue": "This Brazilian acai pulp frozen in a bowl is topped with granola and honey at beach resorts", "correctQuestion": "What is an acai bowl (or acai sorbet)?", "value": 800},
                {"clue": "This Spanish frozen custard made with eggs is similar to gelato but richer", "correctQuestion": "What is crema congelada (or semi-fredo)?", "value": 800},
                {"clue": "This Afghan frozen treat made from pomegranate is served at summer beach festivals", "correctQuestion": "What is pomegranate sorbet?", "value": 800},
                {"clue": "This process where nitrogen gas instantly freezes ice cream creates ultra-smooth texture", "correctQuestion": "What is liquid nitrogen freezing (or cryogenic freezing)?", "value": 800},
                {"clue": "This fiber from chicory root improves texture in reduced-fat ice cream products", "correctQuestion": "What is inulin (or chicory fiber)?", "value": 800},
                {"clue": "This Mexican frozen treat made from tequila and lime is served in shot glass portions", "correctQuestion": "What is a frozen margarita popsicle (or paleta)?", "value": 800},
                {"clue": "This coconut-based frozen dessert from Southeast Asia is blended with fresh fruits", "correctQuestion": "What is coconut milk sorbet?", "value": 800},
                {"clue": "This technique of hand-rolling ice cream in liquid nitrogen creates instant texture", "correctQuestion": "What is nitrogen roll ice cream?", "value": 800},
                {"clue": "This Polish frozen dessert made with fruit puree and whipped cream is lighter than ice cream", "correctQuestion": "What is semi-fredo (or frozen mousse)?", "value": 800},
                {"clue": "This pectin derived from fruit peels stabilizes texture in sorbet-based frozen treats", "correctQuestion": "What is fruit pectin (or natural gelling agent)?", "value": 800},
                {"clue": "This Australian frozen dessert made with gelatin and fruit juice has a jelly-like texture", "correctQuestion": "What is an icy pole?", "value": 800},
                {"clue": "This starch from potatoes acts as a binder in premium artisanal ice cream formulas", "correctQuestion": "What is potato starch (or modified food starch)?", "value": 800},
                {"clue": "This Vietnamese frozen treat made from condensed milk and fruit is served in glass bowls", "correctQuestion": "What is Vietnamese ice cream (or kem)?", "value": 800},
                {"clue": "This equilibrium temperature is when melting ice cream reaches the same temp as beach air", "correctQuestion": "What is about 90+ degrees Fahrenheit?", "value": 800},
                {"clue": "This New Zealand frozen yogurt made with native fruits has natural probiotics", "correctQuestion": "What is kiwifruit frozen yogurt?", "value": 800},
                {"clue": "This crystalline structure forms when ice cream temperature fluctuates during storage", "correctQuestion": "What is ice recrystallization?", "value": 800},
                {"clue": "This ingredient sourced from locust bean stabilizes texture without artificial additives", "correctQuestion": "What is locust bean gum (or carob gum)?", "value": 800},
                {"clue": "This Spanish frozen chocolate thickened with potato starch is eaten with a spoon", "correctQuestion": "What is chocolate ices (or chocolate helado)?", "value": 800},
                {"clue": "This Antarctic ice cream technique uses wind-chill to instantly freeze cream mixtures", "correctQuestion": "What is natural wind-chill freezing?", "value": 800},
            ],
            "level_5_hard_1000": [
                {"clue": "This isomaltose sugar alcohol used in low-calorie ice cream has higher sweetness than sucrose", "correctQuestion": "What is isomaltulose (or isomalt)?", "value": 1000},
                {"clue": "This crystalline amino acid enhances cold perception and throat-cooling sensation in frozen treats", "correctQuestion": "What is L-menthol (or menthol)?", "value": 1000},
                {"clue": "This hydrocolloid polymer derived from brown algae creates smooth texture in no-churn ice cream", "correctQuestion": "What is sodium alginate (or algin)?", "value": 1000},
                {"clue": "This bioactive compound in pomegranate-based sorbets acts as natural preservative and antioxidant", "correctQuestion": "What is punicalagin (or ellagic acid)?", "value": 1000},
                {"clue": "This theobromine derivative in chocolate ice cream increases serotonin and dopamine production", "correctQuestion": "What is phenylethylamine (or theobromine)?", "value": 1000},
                {"clue": "This glass transition temperature determines when frozen desserts become brittle during storage", "correctQuestion": "What is approximately -40 degrees Celsius?", "value": 1000},
                {"clue": "This synergistic combination of guar and xanthan gums creates ideal viscosity without mouth-coating", "correctQuestion": "What is the gum synergy ratio (typically 2:1 guar to xanthan)?", "value": 1000},
                {"clue": "This palmitoyl oligopeptide naturally derived from sea urchin enhances creaminess perception", "correctQuestion": "What is sea urchin peptide (or lipid-based emulsifier)?", "value": 1000},
                {"clue": "This pH buffer maintains 6.8-7.2 range in ice cream to prevent protein denaturation during freezing", "correctQuestion": "What is sodium phosphate (or sodium citrate)?", "value": 1000},
                {"clue": "This sucrose polyester developed for fat-free ice cream passes through digestive system unchanged", "correctQuestion": "What is olestra (or sucrose polyester)?", "value": 1000},
                {"clue": "This polysaccharide from tamarind seeds creates smooth, elastic texture in traditional Indian kulfi", "correctQuestion": "What is tamarind gum (or tamarind kernel powder)?", "value": 1000},
                {"clue": "This fermentation byproduct of Lactobacillus creates natural cryoprotectant in frozen yogurt", "correctQuestion": "What is D-lactic acid?", "value": 1000},
                {"clue": "This critical micelle concentration determines emulsifier efficacy in beach-resistant ice cream formulas", "correctQuestion": "What is approximately 0.06-0.1 millimolar?", "value": 1000},
                {"clue": "This quinone compound from dragon fruit creates color stability in pink-colored sorbets", "correctQuestion": "What is betalain (or betacyanin)?", "value": 1000},
                {"clue": "This rheological property measured in Pascal-seconds determines ice cream spreadability at serving temp", "correctQuestion": "What is dynamic viscosity?", "value": 1000},
                {"clue": "This anthocyanin antioxidant from blueberries maintains color in frozen treats without artificial dyes", "correctQuestion": "What is malvidin (or delphinidin)?", "value": 1000},
                {"clue": "This enzyme derived from papaya breaks down milk proteins in vegan frozen custard bases", "correctQuestion": "What is papain (or protease enzyme)?", "value": 1000},
                {"clue": "This surfactant molecule arranges in dual-orientation at oil-water interface in gelato", "correctQuestion": "What is a lipophilic-hydrophilic molecular structure?", "value": 1000},
                {"clue": "This cryoscopic constant determines freezing point depression slope in ice cream base formulas", "correctQuestion": "What is 1.86 degrees Celsius (per osmol)?", "value": 1000},
                {"clue": "This pectic enzyme from melon seeds stabilizes texture in frozen fruit custard desserts", "correctQuestion": "What is pectinase (or pectin-degrading enzyme)?", "value": 1000},
                {"clue": "This hydrophilic polymer from seaweed creates cling-free surface on beach ice cream bars", "correctQuestion": "What is fucoidan (or brown algae polysaccharide)?", "value": 1000},
                {"clue": "This lipase enzyme from cow milk creates fatty acid profile in aged gelato bases", "correctQuestion": "What is milk lipase (or tributyrinase)?", "value": 1000},
                {"clue": "This flavan-3-ol compound in dark chocolate sorbet has vasodilation properties", "correctQuestion": "What is epicatechin (or catechin)?", "value": 1000},
                {"clue": "This maillard reaction product creates caramel notes in dulce de leche ice cream during production", "correctQuestion": "What is methylglyoxal (or advanced glycation end product)?", "value": 1000},
                {"clue": "This critical point in phase diagram determines texture stability during partial thaw-refroze cycles", "correctQuestion": "What is the eutectic point (approximately -21.2 degrees Celsius)?", "value": 1000},
                {"clue": "This chitosan oligomer derived from shrimp shells acts as natural antimicrobial in frozen dairy", "correctQuestion": "What is chitosan (or chitin-based antimicrobial)?", "value": 1000},
                {"clue": "This zeta potential measurement in millivolts determines emulsion stability in sorbet bases", "correctQuestion": "What is -30 to -50 millivolts?", "value": 1000},
                {"clue": "This isoflavone from soy creates protein matrix in artisanal vegan ice cream alternatives", "correctQuestion": "What is genistein (or daidzein)?", "value": 1000},
                {"clue": "This xylose derivative acts as osmotically active sugar alcohol in reduced-calorie beach frozen treats", "correctQuestion": "What is xylitol (or sorbitol derivative)?", "value": 1000},
                {"clue": "This colloidal suspension of ice crystals in concentrated sugar solution defines classic gelato structure", "correctQuestion": "What is the colloidal ice-sugar matrix?", "value": 1000},
            ],
            "level_6_expert_1200": [
                {"clue": "This Van der Waals force between hydrophobic tails of amphiphilic molecules creates emulsion stability", "correctQuestion": "What is London dispersion force (or hydrophobic interaction)?", "value": 1200},
                {"clue": "This casein micelle phosphate-induced precipitation occurs at pH 4.6 in acidic frozen yogurt bases", "correctQuestion": "What is isoelectric point precipitation?", "value": 1200},
                {"clue": "This rate constant for Ostwald ripening determines size distribution of ice crystals in beach ice cream", "correctQuestion": "What is the temperature-dependent diffusion coefficient?", "value": 1200},
                {"clue": "This Born-Haber cycle thermodynamic calculation predicts enthalpy change during ice crystal nucleation", "correctQuestion": "What is the lattice energy calculation?", "value": 1200},
                {"clue": "This Stokes settling velocity equation predicts particle sedimentation in non-Newtonian ice cream flow", "correctQuestion": "What is the modified Stokes law for complex fluids?", "value": 1200},
                {"clue": "This Monte Carlo simulation predicts molecular arrangement of surfactants at ice-liquid interface", "correctQuestion": "What is molecular dynamics modeling?", "value": 1200},
                {"clue": "This Faraday cage effect prevents ice recrystallization through cryoprotectant molecule orientation", "correctQuestion": "What is the cryoprotective hydration shell?", "value": 1200},
                {"clue": "This Deborah number (ratio of relaxation time to observation time) predicts viscoelasticity of gelato", "correctQuestion": "What is the dimensionless ratio for rheological classification?", "value": 1200},
                {"clue": "This Boltzmann distribution describes thermal energy allocation between solid-liquid ice phases at serving temp", "correctQuestion": "What is the statistical mechanics phase equilibrium?", "value": 1200},
                {"clue": "This Gibbs free energy calculation determines spontaneity of emulsion formation in cream bases", "correctQuestion": "What is delta-G (ΔG = ΔH - TΔS)?", "value": 1200},
                {"clue": "This Laminar flow regime parameter (Reynolds number) determines churning efficiency in barrel freezers", "correctQuestion": "What is Re <1000 (laminar flow)?", "value": 1200},
                {"clue": "This Brunauer-Emmett-Teller isotherm measures surface area of hydrophobic particle networks in ice cream", "correctQuestion": "What is BET adsorption analysis?", "value": 1200},
                {"clue": "This Scherrer equation from X-ray diffraction calculates ice crystal size distribution in frozen desserts", "correctQuestion": "What is the crystallographic crystallite size calculation?", "value": 1200},
                {"clue": "This Henderson-Hasselbalch equation predicts isoelectric point shifts in milk protein gelato base", "correctQuestion": "What is the pH-dependent protein charge distribution?", "value": 1200},
                {"clue": "This Krafft point temperature determines surfactant micellization threshold in emulsion stability", "correctQuestion": "What is approximately 10-40 degrees Celsius depending on alkyl chain length?", "value": 1200},
                {"clue": "This Bragg's law from X-ray crystallography identifies ice lattice structure in premium aged gelato", "correctQuestion": "What is nλ = 2d sin(θ)?", "value": 1200},
                {"clue": "This capillary pressure across curved ice-liquid interface calculated by Young-Laplace equation affects melting point", "correctQuestion": "What is ΔP = 2γ/r (surface tension over radius)?", "value": 1200},
                {"clue": "This Einstein viscosity equation predicts flow behavior of non-Newtonian ice cream with high ice content", "correctQuestion": "What is the colloidal suspension viscosity model?", "value": 1200},
                {"clue": "This Langmuir monolayer compression isotherm predicts emulsifier surface behavior during ice cream freezing", "correctQuestion": "What is the surface pressure vs molecular area relationship?", "value": 1200},
                {"clue": "This Clausius-Clapeyron equation describes vapor pressure change of water over ice in frozen storage conditions", "correctQuestion": "What is the thermodynamic phase transition prediction?", "value": 1200},
                {"clue": "This Penrose-Michels equation predicts lattice structure of ice crystal networks in hand-churned gelato", "correctQuestion": "What is the hexagonal ice lattice geometry model?", "value": 1200},
                {"clue": "This Smoluchowski coagulation equation predicts particle aggregation kinetics in destabilizing emulsions", "correctQuestion": "What is the colloid collision frequency calculation?", "value": 1200},
                {"clue": "This DLVO theory (Derjaguin-Landau-Verwey-Overbeek) predicts colloidal stability through van der Waals and electrostatic forces", "correctQuestion": "What is the interaction potential between emulsion droplets?", "value": 1200},
                {"clue": "This Avrami kinetics equation predicts crystallization rate during nucleation-controlled gelato freezing", "correctQuestion": "What is the non-isothermal phase transformation rate law?", "value": 1200},
                {"clue": "This Freundlich adsorption isotherm models dye pigment adsorption on gelatin in colored artisanal ice cream", "correctQuestion": "What is the non-linear adsorption equilibrium?", "value": 1200},
                {"clue": "This Young's equation balances interfacial tensions at three-phase contact line in ice cream foam", "correctQuestion": "What is γ_SV - γ_SL = γ_LV cos(θ)?", "value": 1200},
                {"clue": "This Kolmogorov microscale turbulence theory predicts particle sizing in high-shear industrial freezers", "correctQuestion": "What is the smallest dissipative eddy scale calculation?", "value": 1200},
                {"clue": "This Staudinger index (viscosity number) correlates molecular weight of hydrocolloid gums to solution viscosity", "correctQuestion": "What is the polymer-solvent interaction parameter?", "value": 1200},
                {"clue": "This Andrade equation describes viscosity temperature dependence for non-Newtonian ice cream flow at beach temp", "correctQuestion": "What is the exponential viscosity-temperature relationship?", "value": 1200},
                {"clue": "This Raman spectroscopy confirms hydrogen bonding network of water molecules in ice crystal lattice structure", "correctQuestion": "What is vibrational spectroscopy analysis?", "value": 1200},
            ],
        }
    }
    return data

def main():
    questions = generate_beach_ice_cream_questions()

    output_file = r"C:\Users\Eddie Thompson\moe\trivial-tile-trivia-portable\output\beach_ice_cream.json"

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)

    # Verify the output
    total_questions = sum(len(v) for v in questions['audiences'].values())
    print(f"Generated beach_ice_cream.json successfully!")
    print(f"Total questions: {total_questions}")
    print(f"Output file: {output_file}")
    print(f"\nBreakdown by difficulty level:")
    for level, questions_list in questions['audiences'].items():
        print(f"  {level}: {len(questions_list)} questions")

if __name__ == "__main__":
    main()
